name = "wordgarden-worker"
main = "src/index.js"
compatibility_date = "2024-12-11"

[site]
bucket = "./public"

[env.production]
name = "wordgarden-worker-prod"

[[kv_namespaces]]
binding = "WORDGARDEN_KV"
id = "3fbb2e5b596545308726b4efe3977765"
preview_id = "3fbb2e5b596545308726b4efe3977765"

[ai]
binding = "AI"

[[env.production.kv_namespaces]]
binding = "WORDGARDEN_KV"
id = "3fbb2e5b596545308726b4efe3977765"

[env.production.ai]
binding = "AI"

# Secrets should be set via `wrangler secret put`

